version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: circle_testing 

    working_directory: ~/ci-demo

    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}

      - run:
          name: composer install
          working_directory: src
          command: composer install -n --prefer-dist

      - save_cache:
          paths: 
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
          
      - run:
          name: Run PHPUnit
          working_directory: src
          command: ./vendor/bin/phpunit